name: Build-Sign-Release
on:
  push:
    branches:
      - "master"

jobs:
  releaser:
    name: Build, Sign, Release (macosx_arm64, macosx_amd64, linux_amd64)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Yarn Install
        run: yarn
      - name: Import Keychain Certs
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Get macosx arm64 Daemon
        run: wget -O ./src/extraResources/daemon/impervious.zip https://github.com/imperviousai/imp-daemon/releases/download/v1.1.2/impervious_1.1.2_darwin_arm64.zip
      - name: Get macosx arm64 Browser
        run: wget -O ./src/extraResources/browser/Impervious.zip https://github.com/imperviousai/imp-browser/releases/download/0.1.2-alpha/Impervious-macosx_arm64.zip
      - name: Build and Sign (macosx-arm64)
        run: yarn make:mac --arch=arm64
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}

      - name: Get macosx x64 Daemon
        run: wget -O ./src/extraResources/daemon/impervious.zip https://github.com/imperviousai/imp-daemon/releases/download/v1.1.2/impervious_1.1.2_darwin_amd64.zip
      - name: Get macosx x64 Browser
        run: wget -O ./src/extraResources/browser/Impervious.zip https://github.com/imperviousai/imp-browser/releases/download/0.1.2-alpha/Impervious-macosx_amd64.zip
      - name: Build and Sign (macosx-amd64)
        run: yarn make:mac
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}

      - name: Get linux x64 Daemon
        run: wget -O ./src/extraResources/daemon/impervious.zip https://github.com/imperviousai/imp-daemon/releases/download/v1.1.2/impervious_1.1.2_linux_amd64.zip
      - name: Get linux x64 Browser
        run: wget -O ./src/extraResources/browser/Impervious.zip https://github.com/imperviousai/imp-browser/releases/download/0.1.2-alpha/Impervious-linux_amd64.zip
      - name: Build (linux-x64)
        run: yarn make:linux --arch=x64

      - name: "Release artifacts"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.4.2"
          title: "v0.4.2"
          files: |
            out/make/zip/darwin/arm64/*.zip
            out/make/*arm64.dmg
            out/make/zip/darwin/x64/*.zip
            out/make/*x64.dmg
            out/make/zip/linux/x64/*.zip
